export const TRANSCRIPTION_TUNING = {
  speaking: {
    rmsWindowSeconds: 0.5,
    rmsThreshold: 0.012,
    minIntervalMs: 200,
    ratio: 1.25,
  },
  systemTranscribe: {
    minRms: 0.002,
  },
  micTranscribe: {
    minRms: 0.001,
    minSpeakerCoverageSeconds: 0.2,
    minSpeakerCoverageRatio: 0.1,
  },
  chunkFlush: {
    minRms: 0.003,
    minSegmentSeconds: 0.3,
    padSeconds: 0.3,
    maxSegments: 4,
    maxFullCoverageRatio: 0.75,
  },
  attribution: {
    tieMargin: 0.18,
    activityCoverageGap: 0.16,
    proximityDelta: 0.12,
    overlapScoreDelta: 0.06,
  },
  activityPrune: {
    meOverlapRatio: 0.45,
    meMinCoverage: 0.35,
    meCoverageRatio: 1.5,
    meMinCoverageFloor: 0.25,
    themOverlapRatio: 0.8,
    themMinCoverage: 0.75,
    themCoverageRatio: 3.0,
    themMinCoverageFloor: 0.55,
  },
  sourceEchoPrune: {
    maxGapSeconds: 0.35,
    minSimilarity: 0.42,
    minThemCoverage: 0.25,
    maxMeCoverageForEcho: 0.12,
    themCoverageRatio: 1.2,
  },
  transcriptQuality: {
    minWords: 5,
    minOverlapRatio: 0.45,
    qualityDelta: 0.28,
    strongQualityDelta: 0.45,
    strongWordDelta: 4,
    shortSystemWords: 3,
    informativeSystemWords: 6,
    informativeSystemScore: 0.45,
  },
  energyPrune: {
    minOverlapRatio: 0.2,
    dominanceRatio: 1.15,
  },
  competingUtterance: {
    highOverlapRatio: 0.62,
    highOverlapSeconds: 1.2,
    lowOverlapRatio: 0.45,
    tokenSimilarity: 0.28,
    prefixSimilarity: 0.45,
  },
  dominanceSelection: {
    strongCoverage: 0.8,
    strongCoverageRatio: 2.8,
    moderateCoverage: 0.2,
    moderateCoverageRatio: 1.25,
    rmsDominanceRatio: 1.2,
    wordDelta: 3,
    strongWordDelta: 4,
  },
  chunkPreference: {
    minCoverageSeconds: 0.35,
    coverageRatio: 1.2,
  },
  diarization: {
    activityWeight: 0.6,
    minSpeakerOverlapSeconds: 1.2,
    minSpeakerScoreRatio: 0.18,
    minSegmentOverlapSeconds: 0.2,
    minSegmentCoverageRatio: 0.5,
  },
} as const;
